#
# Automatically generated file. DO NOT MODIFY
#

PRODUCT_SOONG_NAMESPACES += \
    vendor/nokia/A1N

PRODUCT_COPY_FILES += \
    vendor/nokia/A1N/proprietary/system_ext/etc/permissions/audiosphere.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/audiosphere.xml \
    vendor/nokia/A1N/proprietary/vendor/etc/A1N/ncf/aux/ISO200_1280x720.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/A1N/ncf/aux/ISO200_1280x720.ncf \
    vendor/nokia/A1N/proprietary/vendor/etc/A1N/ncf/aux/ISO200_1600x1200.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/A1N/ncf/aux/ISO200_1600x1200.ncf \
    vendor/nokia/A1N/proprietary/vendor/etc/A1N/ncf/aux/ISO200_2688x1512.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/A1N/ncf/aux/ISO200_2688x1512.ncf \
    vendor/nokia/A1N/proprietary/vendor/etc/A1N/ncf/aux/ISO200_3200x2400.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/A1N/ncf/aux/ISO200_3200x2400.ncf \
    vendor/nokia/A1N/proprietary/vendor/etc/A1N/ncf/aux/ISO200_3840x2160.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/A1N/ncf/aux/ISO200_3840x2160.ncf \
    vendor/nokia/A1N/proprietary/vendor/etc/A1N/ncf/aux/ISO200_4000x3000.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/A1N/ncf/aux/ISO200_4000x3000.ncf \
    vendor/nokia/A1N/proprietary/vendor/etc/A1N/ncf/rear/ISO200_1280x720.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/A1N/ncf/rear/ISO200_1280x720.ncf \
    vendor/nokia/A1N/proprietary/vendor/etc/A1N/ncf/rear/ISO200_1600x1200.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/A1N/ncf/rear/ISO200_1600x1200.ncf \
    vendor/nokia/A1N/proprietary/vendor/etc/A1N/ncf/rear/ISO200_2688x1512.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/A1N/ncf/rear/ISO200_2688x1512.ncf \
    vendor/nokia/A1N/proprietary/vendor/etc/A1N/ncf/rear/ISO200_3200x2400.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/A1N/ncf/rear/ISO200_3200x2400.ncf \
    vendor/nokia/A1N/proprietary/vendor/etc/A1N/ncf/rear/ISO200_3840x2160.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/A1N/ncf/rear/ISO200_3840x2160.ncf \
    vendor/nokia/A1N/proprietary/vendor/etc/A1N/ncf/rear/ISO200_4000x3000.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/A1N/ncf/rear/ISO200_4000x3000.ncf \
    vendor/nokia/A1N/proprietary/vendor/etc/acdbdata/A1N/Bluetooth_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/A1N/Bluetooth_cal.acdb \
    vendor/nokia/A1N/proprietary/vendor/etc/acdbdata/A1N/General_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/A1N/General_cal.acdb \
    vendor/nokia/A1N/proprietary/vendor/etc/acdbdata/A1N/Global_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/A1N/Global_cal.acdb \
    vendor/nokia/A1N/proprietary/vendor/etc/acdbdata/A1N/Handset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/A1N/Handset_cal.acdb \
    vendor/nokia/A1N/proprietary/vendor/etc/acdbdata/A1N/Hdmi_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/A1N/Hdmi_cal.acdb \
    vendor/nokia/A1N/proprietary/vendor/etc/acdbdata/A1N/Headset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/A1N/Headset_cal.acdb \
    vendor/nokia/A1N/proprietary/vendor/etc/acdbdata/A1N/Speaker_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/A1N/Speaker_cal.acdb \
    vendor/nokia/A1N/proprietary/vendor/etc/acdbdata/A1N/workspaceFile_cal.qwsp:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/A1N/workspaceFile_cal.qwsp \
    vendor/nokia/A1N/proprietary/vendor/etc/acdbdata/adsp_avs_config.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/adsp_avs_config.acdb \
    vendor/nokia/A1N/proprietary/vendor/etc/audio/silence_48k.wav:$(TARGET_COPY_OUT_VENDOR)/etc/audio/silence_48k.wav \
    vendor/nokia/A1N/proprietary/vendor/etc/camera/camera_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/camera_config.xml \
    vendor/nokia/A1N/proprietary/vendor/etc/camera/s5k2l7sa05_a1n_wide_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/s5k2l7sa05_a1n_wide_chromatix.xml \
    vendor/nokia/A1N/proprietary/vendor/etc/camera/s5k3m3sm_a1n_tele_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/s5k3m3sm_a1n_tele_chromatix.xml \
    vendor/nokia/A1N/proprietary/vendor/etc/camera/s5k4e8_a1n_front_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/s5k4e8_a1n_front_chromatix.xml \
    vendor/nokia/A1N/proprietary/vendor/etc/init/android.hardware.gatekeeper@1.0-service-qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.gatekeeper@1.0-service-qti.rc \
    vendor/nokia/A1N/proprietary/vendor/etc/init/android.hardware.keymaster@3.0-service-qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.keymaster@3.0-service-qti.rc \
    vendor/nokia/A1N/proprietary/vendor/etc/init/vendor.fih.hardware.ifaa@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.fih.hardware.ifaa@1.0-service.rc \
    vendor/nokia/A1N/proprietary/vendor/etc/init/vendor.qti.hardware.soter@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.soter@1.0-service.rc \
    vendor/nokia/A1N/proprietary/vendor/etc/sensors/hals.conf:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/hals.conf \
    vendor/nokia/A1N/proprietary/vendor/etc/sensors/sensor_def_qcomdev.conf:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/sensor_def_qcomdev.conf \
    vendor/nokia/A1N/proprietary/vendor/etc/wifi/aoa_cldb_falcon.bin:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/aoa_cldb_falcon.bin \
    vendor/nokia/A1N/proprietary/vendor/etc/wifi/aoa_cldb_swl14.bin:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/aoa_cldb_swl14.bin \
    vendor/nokia/A1N/proprietary/vendor/etc/wifi/bdf/CS2_IC_Golden_FWCS_20170315.bin:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/bdf/CS2_IC_Golden_FWCS_20170315.bin \
    vendor/nokia/A1N/proprietary/vendor/etc/wifi/bdf/bdwlan_QC60_CS2_LA1.1_00122.bin:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/bdf/bdwlan_QC60_CS2_LA1.1_00122.bin \
    vendor/nokia/A1N/proprietary/vendor/firmware/TP_Firmware_JDI:$(TARGET_COPY_OUT_VENDOR)/firmware/TP_Firmware_JDI \
    vendor/nokia/A1N/proprietary/vendor/firmware/TP_Firmware_LG4946:$(TARGET_COPY_OUT_VENDOR)/firmware/TP_Firmware_LG4946 \
    vendor/nokia/A1N/proprietary/vendor/firmware/a530_pfp.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a530_pfp.fw \
    vendor/nokia/A1N/proprietary/vendor/firmware/a530_pm4.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a530_pm4.fw \
    vendor/nokia/A1N/proprietary/vendor/firmware/a540_gpmu.fw2:$(TARGET_COPY_OUT_VENDOR)/firmware/a540_gpmu.fw2 \
    vendor/nokia/A1N/proprietary/vendor/firmware/a540_zap.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/a540_zap.b00 \
    vendor/nokia/A1N/proprietary/vendor/firmware/a540_zap.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/a540_zap.b01 \
    vendor/nokia/A1N/proprietary/vendor/firmware/a540_zap.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/a540_zap.b02 \
    vendor/nokia/A1N/proprietary/vendor/firmware/a540_zap.elf:$(TARGET_COPY_OUT_VENDOR)/firmware/a540_zap.elf \
    vendor/nokia/A1N/proprietary/vendor/firmware/a540_zap.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/a540_zap.mdt \
    vendor/nokia/A1N/proprietary/vendor/firmware/cpp_firmware_v1_10_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_10_0.fw \
    vendor/nokia/A1N/proprietary/vendor/firmware/cpp_firmware_v1_12_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_12_0.fw \
    vendor/nokia/A1N/proprietary/vendor/firmware/cpp_firmware_v1_1_1.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_1_1.fw \
    vendor/nokia/A1N/proprietary/vendor/firmware/cpp_firmware_v1_1_6.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_1_6.fw \
    vendor/nokia/A1N/proprietary/vendor/firmware/cpp_firmware_v1_2_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_2_0.fw \
    vendor/nokia/A1N/proprietary/vendor/firmware/cpp_firmware_v1_4_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_4_0.fw \
    vendor/nokia/A1N/proprietary/vendor/firmware/cpp_firmware_v1_5_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_5_0.fw \
    vendor/nokia/A1N/proprietary/vendor/firmware/cpp_firmware_v1_5_1.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_5_1.fw \
    vendor/nokia/A1N/proprietary/vendor/firmware/cpp_firmware_v1_5_2.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_5_2.fw \
    vendor/nokia/A1N/proprietary/vendor/firmware/cpp_firmware_v1_6_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_6_0.fw \
    vendor/nokia/A1N/proprietary/vendor/firmware/cpp_firmware_v1_8_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_8_0.fw \
    vendor/nokia/A1N/proprietary/vendor/firmware/ipa_fws.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/ipa_fws.b00 \
    vendor/nokia/A1N/proprietary/vendor/firmware/ipa_fws.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/ipa_fws.b01 \
    vendor/nokia/A1N/proprietary/vendor/firmware/ipa_fws.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/ipa_fws.b02 \
    vendor/nokia/A1N/proprietary/vendor/firmware/ipa_fws.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/ipa_fws.b03 \
    vendor/nokia/A1N/proprietary/vendor/firmware/ipa_fws.b04:$(TARGET_COPY_OUT_VENDOR)/firmware/ipa_fws.b04 \
    vendor/nokia/A1N/proprietary/vendor/firmware/ipa_fws.elf:$(TARGET_COPY_OUT_VENDOR)/firmware/ipa_fws.elf \
    vendor/nokia/A1N/proprietary/vendor/firmware/ipa_fws.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/ipa_fws.mdt \
    vendor/nokia/A1N/proprietary/vendor/firmware/leia_pfp_470.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/leia_pfp_470.fw \
    vendor/nokia/A1N/proprietary/vendor/firmware/leia_pm4_470.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/leia_pm4_470.fw \
    vendor/nokia/A1N/proprietary/vendor/firmware/tfa98xx.cnt:$(TARGET_COPY_OUT_VENDOR)/firmware/tfa98xx.cnt \
    vendor/nokia/A1N/proprietary/vendor/usr/idc/goodix_fp.idc:$(TARGET_COPY_OUT_VENDOR)/usr/idc/goodix_fp.idc \
    vendor/nokia/A1N/proprietary/vendor/usr/keylayout/goodix_fp.kl:$(TARGET_COPY_OUT_VENDOR)/usr/keylayout/goodix_fp.kl

PRODUCT_PACKAGES += \
    sound_trigger.primary.msm8998 \
    vendor.qti.hardware.soter@1.0-impl \
    libacdb-fts \
    libacdbloader \
    libacdbrtac \
    libadiertac \
    libaudcal \
    libaudio_log_utils \
    libaudioalsa \
    libaudioconfigstore \
    libaudioparsers \
    libfastcvadsp_stub \
    libgcs-calwrapper \
    libgcs-ipc \
    libgcs-osal \
    libgcs \
    libmmcamera2_frame_algorithm \
    libmmcamera2_is \
    libmmcamera2_q3a_core \
    libmmcamera2_stats_algorithm \
    libmmcamera2_stats_lib \
    libmmcamera_dbg \
    libmmcamera_faceproc \
    libmmcamera_faceproc2 \
    libmmcamera_tintless_algo \
    libmmcamera_tintless_bg_pca_algo \
    libqtigef \
    libseemore \
    libsensor1 \
    libsensor_reg \
    libsns_low_lat_stream_stub \
    libssc_default_listener \
    libvideoutils \
    sensor_calibrate \
    sensors.ssc \
    vendor.fih.hardware.ifaa@1.0 \
    vendor.qti.hardware.soter@1.0 \
    camera.msm8998 \
    libactuator_ak7345 \
    libactuator_ak7371 \
    libactuator_ak7371_tele_a1n \
    libactuator_ak7371_wide_a1n \
    libadm \
    libadpcmdec \
    libarcsoft_beautyshot \
    libarcsoft_beautyshot_image_algorithm \
    libarcsoft_beautyshot_video_algorithm \
    libarcsoft_dualcam_refocus \
    libarcsoft_night_shot \
    libarcsoft_picselfie_algorithm \
    libarcsoft_smart_denoise \
    libchromatix_s5k2l7sa05_a1n_wide_4k_preview_3a \
    libchromatix_s5k2l7sa05_a1n_wide_4k_video_3a \
    libchromatix_s5k2l7sa05_a1n_wide_common \
    libchromatix_s5k2l7sa05_a1n_wide_cpp_hfr_60 \
    libchromatix_s5k2l7sa05_a1n_wide_cpp_liveshot \
    libchromatix_s5k2l7sa05_a1n_wide_cpp_preview \
    libchromatix_s5k2l7sa05_a1n_wide_cpp_snapshot \
    libchromatix_s5k2l7sa05_a1n_wide_cpp_video \
    libchromatix_s5k2l7sa05_a1n_wide_cpp_video_4k \
    libchromatix_s5k2l7sa05_a1n_wide_default_preview_3a \
    libchromatix_s5k2l7sa05_a1n_wide_default_video_3a \
    libchromatix_s5k2l7sa05_a1n_wide_hfr_60 \
    libchromatix_s5k2l7sa05_a1n_wide_hfr_60_3a \
    libchromatix_s5k2l7sa05_a1n_wide_postproc \
    libchromatix_s5k2l7sa05_a1n_wide_preview \
    libchromatix_s5k2l7sa05_a1n_wide_snapshot \
    libchromatix_s5k2l7sa05_a1n_wide_snapshot_longexposure \
    libchromatix_s5k2l7sa05_a1n_wide_versions \
    libchromatix_s5k2l7sa05_a1n_wide_video \
    libchromatix_s5k2l7sa05_a1n_wide_video_4k \
    libchromatix_s5k2l7sa05_a1n_wide_zsl_preview_3a \
    libchromatix_s5k2l7sa05_a1n_wide_zsl_video_3a \
    libchromatix_s5k3m3sm_a1n_tele_4k_preview_3a \
    libchromatix_s5k3m3sm_a1n_tele_4k_video_3a \
    libchromatix_s5k3m3sm_a1n_tele_common \
    libchromatix_s5k3m3sm_a1n_tele_cpp_hfr_120 \
    libchromatix_s5k3m3sm_a1n_tele_cpp_hfr_60 \
    libchromatix_s5k3m3sm_a1n_tele_cpp_hfr_90 \
    libchromatix_s5k3m3sm_a1n_tele_cpp_liveshot \
    libchromatix_s5k3m3sm_a1n_tele_cpp_preview \
    libchromatix_s5k3m3sm_a1n_tele_cpp_snapshot \
    libchromatix_s5k3m3sm_a1n_tele_cpp_video \
    libchromatix_s5k3m3sm_a1n_tele_cpp_video_4k \
    libchromatix_s5k3m3sm_a1n_tele_default_preview_3a \
    libchromatix_s5k3m3sm_a1n_tele_default_video \
    libchromatix_s5k3m3sm_a1n_tele_default_video_3a \
    libchromatix_s5k3m3sm_a1n_tele_hfr_120 \
    libchromatix_s5k3m3sm_a1n_tele_hfr_120_3a \
    libchromatix_s5k3m3sm_a1n_tele_hfr_60 \
    libchromatix_s5k3m3sm_a1n_tele_hfr_60_3a \
    libchromatix_s5k3m3sm_a1n_tele_hfr_90 \
    libchromatix_s5k3m3sm_a1n_tele_hfr_90_3a \
    libchromatix_s5k3m3sm_a1n_tele_liveshot \
    libchromatix_s5k3m3sm_a1n_tele_postproc \
    libchromatix_s5k3m3sm_a1n_tele_preview \
    libchromatix_s5k3m3sm_a1n_tele_snapshot \
    libchromatix_s5k3m3sm_a1n_tele_versions \
    libchromatix_s5k3m3sm_a1n_tele_video_4k \
    libchromatix_s5k3m3sm_a1n_tele_zsl_preview_3a \
    libchromatix_s5k3m3sm_a1n_tele_zsl_video_3a \
    libchromatix_s5k4e8_a1n_front_4k_preview_3a \
    libchromatix_s5k4e8_a1n_front_4k_video_3a \
    libchromatix_s5k4e8_a1n_front_common \
    libchromatix_s5k4e8_a1n_front_cpp_hfr_120 \
    libchromatix_s5k4e8_a1n_front_cpp_hfr_60 \
    libchromatix_s5k4e8_a1n_front_cpp_hfr_90 \
    libchromatix_s5k4e8_a1n_front_cpp_liveshot \
    libchromatix_s5k4e8_a1n_front_cpp_preview \
    libchromatix_s5k4e8_a1n_front_cpp_snapshot \
    libchromatix_s5k4e8_a1n_front_cpp_video \
    libchromatix_s5k4e8_a1n_front_cpp_video_4k \
    libchromatix_s5k4e8_a1n_front_default_preview_3a \
    libchromatix_s5k4e8_a1n_front_default_video \
    libchromatix_s5k4e8_a1n_front_default_video_3a \
    libchromatix_s5k4e8_a1n_front_hfr_120 \
    libchromatix_s5k4e8_a1n_front_hfr_120_3a \
    libchromatix_s5k4e8_a1n_front_hfr_60 \
    libchromatix_s5k4e8_a1n_front_hfr_60_3a \
    libchromatix_s5k4e8_a1n_front_hfr_90 \
    libchromatix_s5k4e8_a1n_front_hfr_90_3a \
    libchromatix_s5k4e8_a1n_front_liveshot \
    libchromatix_s5k4e8_a1n_front_postproc \
    libchromatix_s5k4e8_a1n_front_preview \
    libchromatix_s5k4e8_a1n_front_snapshot \
    libchromatix_s5k4e8_a1n_front_versions \
    libchromatix_s5k4e8_a1n_front_video_4k \
    libchromatix_s5k4e8_a1n_front_zsl_preview_3a \
    libchromatix_s5k4e8_a1n_front_zsl_video_3a \
    libdepthmapwrapper \
    libdrc \
    libfih_camera_effect \
    libhal_dbg \
    libjpegdhw \
    libjpegdmahw \
    libjpegehw \
    libmm-qcamera \
    libmmcamera2_c2d_module \
    libmmcamera2_cpp_module \
    libmmcamera2_iface_modules \
    libmmcamera2_imglib_modules \
    libmmcamera2_isp_modules \
    libmmcamera2_mct \
    libmmcamera2_mct_shimlayer \
    libmmcamera2_pp_buf_mgr \
    libmmcamera2_pproc_modules \
    libmmcamera2_sensor_modules \
    libmmcamera2_stats_modules \
    libmmcamera_arcsoftbokeh_lib \
    libmmcamera_bokeh \
    libmmcamera_csidtg \
    libmmcamera_depth_map \
    libmmcamera_dummyalgo \
    libmmcamera_dw9761b_2d_eeprom \
    libmmcamera_eebinparse \
    libmmcamera_eeprom_util \
    libmmcamera_eztune_module \
    libmmcamera_facedetection_lib \
    libmmcamera_hdr_gb_lib \
    libmmcamera_hvx_add_constant \
    libmmcamera_hvx_grid_sum \
    libmmcamera_imglib \
    libmmcamera_imglib_faceproc_adspstub \
    libmmcamera_interface \
    libmmcamera_isp_abf48 \
    libmmcamera_isp_aec_bg_stats47 \
    libmmcamera_isp_bf_stats47 \
    libmmcamera_isp_bg_stats46 \
    libmmcamera_isp_bhist_stats44 \
    libmmcamera_isp_black_level48 \
    libmmcamera_isp_bpc48 \
    libmmcamera_isp_cac47 \
    libmmcamera_isp_chroma_enhan40 \
    libmmcamera_isp_chroma_suppress40 \
    libmmcamera_isp_clamp_encoder40 \
    libmmcamera_isp_clamp_video40 \
    libmmcamera_isp_clamp_viewfinder40 \
    libmmcamera_isp_color_correct46 \
    libmmcamera_isp_color_xform_encoder46 \
    libmmcamera_isp_color_xform_video46 \
    libmmcamera_isp_color_xform_viewfinder46 \
    libmmcamera_isp_cs_stats46 \
    libmmcamera_isp_demosaic48 \
    libmmcamera_isp_demux48 \
    libmmcamera_isp_fovcrop_encoder46 \
    libmmcamera_isp_fovcrop_video46 \
    libmmcamera_isp_fovcrop_viewfinder46 \
    libmmcamera_isp_gamma44 \
    libmmcamera_isp_gic48 \
    libmmcamera_isp_gtm46 \
    libmmcamera_isp_hdr48 \
    libmmcamera_isp_hdr_be_stats46 \
    libmmcamera_isp_hdr_bhist_stats44 \
    libmmcamera_isp_ihist_stats46 \
    libmmcamera_isp_linearization40 \
    libmmcamera_isp_ltm47 \
    libmmcamera_isp_luma_adaptation40 \
    libmmcamera_isp_mce40 \
    libmmcamera_isp_mesh_rolloff44 \
    libmmcamera_isp_pdaf48 \
    libmmcamera_isp_pedestal_correct46 \
    libmmcamera_isp_rs_stats46 \
    libmmcamera_isp_scaler_encoder46 \
    libmmcamera_isp_scaler_video46 \
    libmmcamera_isp_scaler_viewfinder46 \
    libmmcamera_isp_sce40 \
    libmmcamera_isp_snr47 \
    libmmcamera_isp_sub_module \
    libmmcamera_m24c64s_tele_a1n_eeprom \
    libmmcamera_m24c64t_wide_a1n_eeprom \
    libmmcamera_pdaf \
    libmmcamera_pdafcamif \
    libmmcamera_ppbase_module \
    libmmcamera_ppeiscore \
    libmmcamera_s5k2l7sa05_wide_a1n \
    libmmcamera_s5k3m3sm_tele_a1n \
    libmmcamera_s5k4e8_front_a1n \
    libmmcamera_s5k4e8_front_a1n_eeprom \
    libmmcamera_sw2d_lib \
    libmmcamera_thread_services \
    libmmcamera_truly_cma481_eeprom \
    libmmcamera_truly_cmb433_eeprom \
    libmmcamera_tuning \
    libmmcamera_tuning_lookup \
    libmmjpeg \
    libmmjpeg_interface \
    libmmlib2d_interface \
    libmmqjpeg_codec \
    libmmqjpegdma \
    libmpbase \
    libois_bu63165 \
    libois_lc898122 \
    libqomx_core \
    libqomx_jpegdec \
    libqomx_jpegenc \
    libqomx_jpegenc_pipe \
    libremosaic_daemon \
    libsmwrapper \
    libsurround_3mic_proc \
    android.hardware.gatekeeper@1.0-impl-qti \
    android.hardware.keymaster@3.0-impl-qti \
    fingerprint.default \
    gatekeeper.msm8998 \
    keystore.msm8998 \
    libgf_ca \
    libgf_hal \
    libgoodixhwfingerprint \
    libkeymasterdeviceutils \
    libkeymasterprovision \
    libkeymasterutils \
    libvendor.goodix.hardware.fingerprintextension@1.0 \
    capi_v2_aptX_Classic \
    capi_v2_aptX_HD \
    libFastRPC_AUE_Forward_skel \
    libFastRPC_UTF_Forward_Qtc2_skel \
    libFastRPC_UTF_Forward_skel \
    libadsp_fd_skel \
    libadsp_hvx_add_constant \
    libadsp_hvx_skel \
    libapps_mem_heap \
    libdspCV_skel \
    libfastcvadsp \
    libfastcvadsp_skel \
    libsns_low_lat_stream_skel \
    libvpp_frc \
    libvpp_svc_skel \
    vendor.qti.hardware.soter@1.0 \
    HotwordEnrollmentOKGoogleWCD9335 \
    HotwordEnrollmentTGoogleWCD9335 \
    HotwordEnrollmentXGoogleWCD9335 \
    audiosphere \
    vendor.qti.hardware.soter-V1.0-java \
    android.hardware.gatekeeper@1.0-service-qti \
    android.hardware.keymaster@3.0-service-qti \
    vendor.fih.hardware.ifaa@1.0-service \
    vendor.qti.hardware.soter@1.0-service \
    mm-qcamera-app \
    qdcm_calib_data_LGD_cmd_mode_dsc_dsi_panel.xml \
    sensors.qti \
    vendor.qti.hardware.soter@1.0-provision
